### ISSUE TITLE
prefix option

### ISSUE THREAD

**Issue by roccomuso** [jhermsmeier/hxd#2]
Might be useful a `prefix` option like in [hexer](https://github.com/jcorbin/hexer) ?
I'm considering the idea to switch to hxd my [netcat](/roccomuso/netcat) project

**Comment by jhermsmeier** [comment]
Could you elaborate on the use-case of a prefix? I'm not sure how much sense it'd make to put into `hxd`, and understanding the use might help. Couldn't you just use a transform stream to prefix the lines?

**Comment by jhermsmeier** [comment]
Ping @roccomuso

**Comment by roccomuso** [comment]
yes I could. It's just a parameter. Might be considered useful or not

**Comment by jhermsmeier** [comment]
This is available & published in `hxd@1.6.0` now
