### ISSUE TITLE
How do I read the hex values and the decoded text through javascript?

### ISSUE THREAD

**Issue by Stanlyhalo** [jhermsmeier/hxd#3]
I have an electron app with nodeIntegration into the webview, and I want to be able to get the "decoded text" maybe as a json variable for each line and same goes for the hex values, how can I do this?

**Comment by jhermsmeier** [comment]
Hi @Stanlyhalo, similar to the [usage example](https://github.com/jhermsmeier/hxd#module-usage) you'd instantiate a stream, write to it what you want to display, and then read it back from the stream. You can then split the resulting string into lines or whatever you want. For example:

```js
var Hxd = require( 'hxd' )

function hexdump( input, callback ) {

  var dump = ''
  var hxd = new Hxd({
    dedupe: false,
    colors: false,
    ascii: true,
  })

  hxd.on( 'readable', function() {
    var chunk = null
    while(( chunk = this.read() )) {
      dump += chunk
    }
  })

  hxd.once( 'end', () => {
    var lines = dump.trim().split( /\r?\n/g )
    callback( null, lines )
  })

  hxd.end( input )

}
```
